//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string NoOfGuest { get; set; }
        public string RoomType { get; set; }
        public string RoomFloor { get; set; }
        public string AptNo { get; set; }
        public string TotalBill { get; set; }
        public string PaymentType { get; set; }
        public string CardNo { get; set; }
    }
}
